repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.23.3
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^((myhome|tests)/.+)?[^/]+\.py$
        exclude: ^myhome/gen/
  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=hass,alot,datas,dof,dur,ether,farenheit,hist,iff,ines,ist,lightsensor,mut,nd,pres,referer,ser,serie,te,technik,ue,uint,visability,wan,wanna,withing,iam,incomfort,ba
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types: [csv, json]
        exclude: ^(tests/fixtures/|myhome/gen/)
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - pycodestyle==2.7.0
          - pyflakes==2.3.1
          - flake8-docstrings==1.6.0
          - pydocstyle==6.0.0
          - flake8-comprehensions==3.5.0
          - flake8-noqa==1.1.0
          - mccabe==0.6.1
        files: ^(myhome|tests)/.+\.py$
        exclude: ^myhome/gen/
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args:
          - --quiet
          - --format=custom
          - --configfile=tests/bandit.yaml
        files: ^(myhome|tests)/.+\.py$
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
          - --branch=rc
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.1
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        stages: [manual]
  - repo: https://github.com/cdce8p/python-typing-update
    rev: v0.3.5
    hooks:
      # Run `python-typing-update` hook manually from time to time
      # to update python typing syntax.
      # Will require manual work, before submitting changes!
      - id: python-typing-update
        stages: [manual]
        args:
          - --py38-plus
          - --force
          - --keep-updates
        files: ^(myhome|tests)/.+\.py$
