"""
    MyHomeSERVER1 API

    API provided by the Bticino MyHomeSERVER1 system and used by the MyHomeUp mobile application  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import myhome._gen
from myhome._gen.model.system_info import SystemInfo


class TestSystemInfo(unittest.TestCase):
    """SystemInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemInfo(self):
        """Test SystemInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SystemInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
