"""
    MyHomeSERVER1 API

    API provided by the Bticino MyHomeSERVER1 system and used by the MyHomeUp mobile application  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import myhome._gen
from myhome._gen.model.serial_server import SerialServer


class TestSerialServer(unittest.TestCase):
    """SerialServer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSerialServer(self):
        """Test SerialServer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SerialServer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
