"""
    MyHomeSERVER1 API

    API provided by the Bticino MyHomeSERVER1 system and used by the MyHomeUp mobile application  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""



import datetime
import unittest

import myhome._gen
from myhome._gen.models.init_check_response import InitCheckResponse  # noqa: E501
from myhome._gen.rest import ApiException


class TestInitCheckResponse(unittest.TestCase):
    """InitCheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InitCheckResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = myhome._gen.models.init_check_response.InitCheckResponse()  # noqa: E501
        if include_optional :
            return InitCheckResponse(
                actual = 1.337, 
                init_check = True, 
                state_init = '', 
                total = 1.337
            )
        else :
            return InitCheckResponse(
                actual = 1.337,
                init_check = True,
                state_init = '',
                total = 1.337,
        )

    def testInitCheckResponse(self):
        """Test InitCheckResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
