"""
    MyHomeSERVER1 API

    API provided by the Bticino MyHomeSERVER1 system and used by the MyHomeUp mobile application  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import myhome._gen
from myhome._gen.model.object_value_dimmer import ObjectValueDimmer
from myhome._gen.model.object_value_light import ObjectValueLight
from myhome._gen.model.object_value_shutter import ObjectValueShutter
from myhome._gen.model.object_value_thermostat import ObjectValueThermostat

globals()['ObjectValueDimmer'] = ObjectValueDimmer
globals()['ObjectValueLight'] = ObjectValueLight
globals()['ObjectValueShutter'] = ObjectValueShutter
globals()['ObjectValueThermostat'] = ObjectValueThermostat
from myhome._gen.model.object_value import ObjectValue


class TestObjectValue(unittest.TestCase):
    """ObjectValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectValue(self):
        """Test ObjectValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObjectValue()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
