"""
    MyHomeSERVER1 API

    API provided by the Bticino MyHomeSERVER1 system and used by the MyHomeUp mobile application  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""



import datetime
import unittest

import myhome._gen
from myhome._gen.models.serial_server import SerialServer  # noqa: E501
from myhome._gen.rest import ApiException


class TestSerialServer(unittest.TestCase):
    """SerialServer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test SerialServer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = myhome._gen.models.serial_server.SerialServer()  # noqa: E501
        if include_optional :
            return SerialServer(
                serial_server = ''
            )
        else :
            return SerialServer(
        )

    def testSerialServer(self):
        """Test SerialServer"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
