"""
    MyHomeSERVER1 API

    API provided by the Bticino MyHomeSERVER1 system and used by the MyHomeUp mobile application  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import myhome._gen
from myhome._gen.model.object_value_light import ObjectValueLight


class TestObjectValueLight(unittest.TestCase):
    """ObjectValueLight unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testObjectValueLight(self):
        """Test ObjectValueLight"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ObjectValueLight()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
